### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1.

### ISSUE THREAD

**Issue by styler00dollar** [delta6189/Anime-Sketch-Colorizer#1]
I tried ``test.ipynb``, but it does not seem to work.
```
Loading pretrained Sketch2Color model... Done!
Number of parameters: 63504297
edge.shape
torch.Size([6, 3, 512, 512])
len(color_palette)
9
color_palette[0].shape
torch.Size([1, 3, 512, 512])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-8fab4b12b06a> in <module>()
     28     print("color_palette[0].shape")
     29     print(color_palette[0].shape)
---> 30     input_tensor = torch.cat([edge.cpu()]+color_palette, dim=1).to(device)
     31     fake = netG(input_tensor)
     32     result = torch.cat((reference, edge, fake, real), dim=-1).cpu()

RuntimeError: Sizes of tensors must match except in dimension 1. Got 6 and 1 in dimension 0 (The offending index is 1)
```
All data is in 3 channel RGB. I also tried to modify ``input_tensor = torch.cat([edge.cpu()]+color_palette, dim=1).to(device)`` but I am getting a lot of shape errors within ``netG()``. How are the shapes expected to look like?

Here is my [Google Colab](https://colab.research.google.com/drive/1dca-Z7kr4nqcI4Qt5c13X20CQIZwfeB1?usp=sharing), you can reproduce the behaviour there.

**Comment by delta6189** [comment]
Hi. Thank you for your attention on my work.

It seems I made a mistake on ```test.ipynb```. I uploaded a modified version of ```test.ipynb```. Sorry.

Here is an example created 3 minutes ago from that code. (Reference - Sketch - Colorized)

![ex_screenshot](https://raw.githubusercontent.com/delta6189/Anime-Sketch-Colorizer/master/outputs/sample/Example.png)

Furthermore, please note that I did not use traditional edge detector like ```cv2.canny``` or ```cv2.sobel```. Instead, I trained another model to convert color image to sketch image. The checkpoint file ```color2sketch.pth``` (NOT ```sketch2color.pth```) is the weight of sketch model.

If you have any questions, you are welcome to ask.

Thx.

**Comment by styler00dollar** [comment]
Thanks for the quick response. I tested it and it works now. I primarily just wanted to test if code works and decided to quickly use canny. I didn't notice that the data inside ``test`` will be automatically converted to sketch with
```
img_edge = self.sketch_net(img.unsqueeze(0).to(self.device)).squeeze().permute(1,2,0).cpu().numpy()
```
In case you care, I made a fork and uploaded my Colab version [here](https://github.com/styler00dollar/Colab-Anime-Sketch-Colorizer/blob/master/Colab-Anime-Sketch-Colorizer.ipynb).

**Comment by Finger-tiao** [comment]
> I tried `test.ipynb`, but it does not seem to work.
> 
> ```
> Loading pretrained Sketch2Color model... Done!
> Number of parameters: 63504297
> edge.shape
> torch.Size([6, 3, 512, 512])
> len(color_palette)
> 9
> color_palette[0].shape
> torch.Size([1, 3, 512, 512])
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-28-8fab4b12b06a> in <module>()
>      28     print("color_palette[0].shape")
>      29     print(color_palette[0].shape)
> ---> 30     input_tensor = torch.cat([edge.cpu()]+color_palette, dim=1).to(device)
>      31     fake = netG(input_tensor)
>      32     result = torch.cat((reference, edge, fake, real), dim=-1).cpu()
> 
> RuntimeError: Sizes of tensors must match except in dimension 1. Got 6 and 1 in dimension 0 (The offending index is 1)
> ```
> 
> All data is in 3 channel RGB. I also tried to modify `input_tensor = torch.cat([edge.cpu()]+color_palette, dim=1).to(device)` but I am getting a lot of shape errors within `netG()`. How are the shapes expected to look like?
> 
> Here is my [Google Colab](https://colab.research.google.com/drive/1dca-Z7kr4nqcI4Qt5c13X20CQIZwfeB1?usp=sharing), you can reproduce the behaviour there.

Hi, I have the same error as you but I have no idea to solve it. Could you please tell me how you solved it?
