### ISSUE TITLE
I couldn't color it beautifully

### ISSUE THREAD

**Issue by Foresiver5555** [delta6189/Anime-Sketch-Colorizer#3]
I tried test.ipynb, but it does not seem to work.
It is not displayed properly in the "2.3 Dataset Test" section.

The Script:

```
temp_batch = next(temp_batch_iter)
edge = temp_batch[0]
color = temp_batch[1]
color_palette = temp_batch[2]

plt.figure(figsize=(16, 100))
result =torch.cat([edge, color]+color_palette,dim=-2)
plt.imshow(np.transpose(vutils.make_grid(result, nrow=6, padding=5, normalize=True).cpu(),(1,2,0)))
plt.axis("off")
plt.title("Images")
plt.show()
```

Output:
![test](https://user-images.githubusercontent.com/94363264/141771091-b66ad587-8fb6-49d4-8098-32b6afd0afb5.png)

It cannot be colored exactly like this.
As explained, the model and dataset are "checkpoint" and "Anime Sketch Colorization Pair".

I'm sorry for being an amateur, but I would like to know the solution.

**Comment by delta6189** [comment]
Well, I'm not sure but there are many possibilities.

1. Please check your pytorch version. As the version is updated, some operations may be depreciated or changed and it can lead to unpleased output. Unfortunately, I can not remember the exact version of pytorch of original repository but it would be 1.3.0~1.5.0.
2. Please check whether your input sketch/palette are normalized properly or not. The un-normalized inputs also lead to poor performance.
3. Please check the colorization model is on "eval" mode.

There may be a variety of other causes, but the reasons that come to mind now are the above. 

Thx.

**Comment by Foresiver5555** [comment]
Thank you for the quick answer.
When I checked 2 and 3, it seemed that there was no problem, so I will try the environment for the time being.

I'm sorry that this question hasn't been solved yet, but I've had another error so let me ask you again first.

When I ran "4.1 Show colorization results", an error occurred and I could not save.


The Script:

```
# validation funciton
def save_images(data_loader, model):
    with torch.no_grad():
        # Prepare value counters and timers
        for i, data in enumerate(data_loader, 0):
            # Record time to do forward passes and save images
            start = time.time()
            
            edge = data[0].to(device)
            edge = torch.cat([edge]*6, dim=0)
            real = data[1].to(device)
            real = torch.cat([real]*6, dim=0)
            reference = refer_batch[1].to(device)
            color_palette = refer_batch[2]
            input_tensor = torch.cat([edge.cpu()]+color_palette, dim=1).to(device)
            fake = netG(input_tensor)
            result = torch.cat((reference, edge, fake, real), dim=-1)
            output = vutils.make_grid(result, nrow=1, padding=5, normalize=True).cpu().permute(1,2,0).numpy()
            
            # Save images to file
            save_path = 'outputs/sketch2color/'
            save_name = 'img-{}.jpg'.format(i)
            plt.imsave(arr=output, fname='{}{}'.format(save_path, save_name))

            # Record time to do forward passes and save images
            end = time.time()

            # Print model accuracy -- in the code below, val refers to both value and validation
            print('\rSave: [{0}/{1}]\t'
                'Time {2:0.3f}s \t'
                .format(i+1, len(data_loader), end - start), end='')

with torch.no_grad():
    netG.eval()
    save_images(val_loader, netG)
```

Output:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-6219501b23ea> in <module>
      1 with torch.no_grad():
      2     netG.eval()
----> 3     save_images(val_loader, netG)

<ipython-input-20-8cdd77d9cfbf> in save_images(data_loader, model)
     13             reference = refer_batch[1].to(device)
     14             color_palette = refer_batch[2]
---> 15             input_tensor = torch.cat([edge.cpu()]+color_palette, dim=1).to(device)
     16             fake = netG(input_tensor)
     17             result = torch.cat((reference, edge, fake, real), dim=-1)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 6 and 1 in dimension 0 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
```

**Comment by delta6189** [comment]
Well, I just ran the test.ipynb file, but no errors have occurred...

Please check the size of color_palette tensor, which should have size of [Batch size, Channel, Width, Height]. Here, the channel equals to 3 * (# of clusters).
